name: XpBank
main: me.head_block.xpbank.Main
description: Xp Banking System
version: 1.13
author: McCloud
softdepend: [PlaceholderAPI]

commands: 
  xpbank: 
  xpbal:
  topxp:
  xpbankdebug:
  
permissions: 
  xpbank.use:
    default: true
  xpbank.admin:
    default: op