name: XpBank
main: me.head_block.xpbank.Main
description: Xp Banking System
version: 1.4.2
author: McCloud
api-version: 1.18

commands: 
  xpbank: 
  xpbal:
  
permissions: 
  xpbank.use:
    default: true