name: XpBank
main: me.head_block.xpbank.Main
description: Xp Banking System
version: 1.6
author: McCloud
api-version: 1.18

commands: 
  xpbank: 
  xpbal:
  topxp:
  
permissions: 
  xpbank.use:
    default: true
  xpbank.admin:
    default: op