name: XpBank
main: me.head_block.xpbank.Main
description: Xp Banking System
version: 1.11.0
author: McCloud
api-version: 1.13
softdepend: [PlaceholderAPI]

commands: 
  xpbank: 
  xpbal:
  topxp:
  
permissions: 
  xpbank.use:
    default: true
  xpbank.admin:
    default: op